### ISSUE TITLE
Bugs: incorrect event command crashes app, and dates cause error when loading

### ISSUE THREAD

**Issue by damithc** [badassengineer/ip#4]
Two bugs noticed while testing. The text below show the interactions that lead to the bugs.
```
event return book /at 2022-12-28
Got it. I've added this task:
[E][ ] return book (at: Dec 28 2022)
Now you have 1 tasks in the list.

list
Here are the tasks in your list:

1. [E][ ] return book (at: Dec 28 2022)

todo buy bread
Got it. I've added this task:
[T][ ] buy bread
Now you have 2 tasks in the list.

list
Here are the tasks in your list:

1. [E][ ] return book (at: Dec 28 2022)
2. [T][ ] buy bread
mark 1
Nice! I've marked this task as done:
[E][X] return book (at: Dec 28 2022)


mark 2
Nice! I've marked this task as done:
[T][X] buy bread


list
Here are the tasks in your list:

1. [E][X] return book (at: Dec 28 2022)
2. [T][X] buy bread

deadline finish work
Exception in thread "main" java.time.format.DateTimeParseException: Text 'line finish work' could not be parsed at index 0
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
        at java.base/java.time.LocalDate.parse(LocalDate.java:428)
        at java.base/java.time.LocalDate.parse(LocalDate.java:413)
        at command.Parser.parse(Parser.java:59)
        at command.Ui.command(Ui.java:16)
        at command.Ui.main(Ui.java:45)
        at command.Duke.main(Duke.java:30)
PS C:\Users\dcsdcr\Documents\nBox\nus-tic4001-AY2223S1\ip-JAR-files> java -jar .\roshankumar1991[10-01-2022--03.47.11].jar
Hello! I'm Duke

Let me load the existing data for you (if any)

Please confirm if this current directory is correct.
./data/

If it is, please confirm by typing 'Yes'
If you want to select a different directory, please confirm by typing 'No'

yes
Please confirm if this current file is correct.
duke.txt

If it is, please confirm by typing 'Yes'
If you want to select a different file, please confirm by typing 'No'

yes
Thank you for your response
Exception in thread "main" java.time.format.DateTimeParseException: Text 'Dec 28 2022' could not be parsed at index 0
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
        at java.base/java.time.LocalDate.parse(LocalDate.java:428)
        at java.base/java.time.LocalDate.parse(LocalDate.java:413)
        at command.Parser.parse(Parser.java:59)
        at command.Storage.printFileContents(Storage.java:43)
        at command.Storage.main(Storage.java:81)
        at command.FilePath.main(FilePath.java:149)
        at command.Ui.main(Ui.java:25)
        at command.Duke.main(Duke.java:30)
PS C:\Users\dcsdcr\Documents\nBox\nus-tic4001-AY2223S1\ip-JAR-files>
```

**Comment by damithc** [comment]
Sorry @badassengineer , I posted in the wrong repo. Please ignore.
